# Spring Boot sunucusunun  al??aca?? port
server.port=8080

# Docker ortam?ndaki Kafka sunucusunun adresi
spring.kafka.bootstrap-servers=kafka:29092

# Anomali dinleyicisi i in t ketici grup ID'si
spring.kafka.consumer.group-id=kripto-gozcusu-grup

# Topic'te yeni bir offset bulunmad???nda en ba?tan okumaya ba?la
spring.kafka.consumer.auto-offset-reset=earliest

# Gelen anahtar (key) ve de?er (value) verilerinin format?
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.StringDeserializer
